name: Run unit tests on pr

on:
  push:
    branches-ignore:
      - main

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 19.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm ci

      - name: Build the code
        run: npm run build

      - name: Check format of files
        run: npm run format-check

      - name: Check lint of files
        run: npm run lint
